name: 매일 주식 블로그 쓰기

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write # ⭐️ 쓰기 권한 필수!

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 내 코드 가져오기
      uses: actions/checkout@v3

    - name: 파이썬 설정하기
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 필요한 라이브러리 설치
      run: |
        pip install finance-datareader beautifulsoup4 lxml

    - name: 로봇 실행! (에러나면 멈춰!)
      run: |
        python main.py
        cat index.html # ⭐️ 실행 직후, 파일 내용이 진짜로 바뀌었는지 화면에 출력해보기

    - name: 결과물 저장하고 퇴근하기
      run: |
        git config --global user.name 'StockBot'
        git config --global user.email 'bot@noreply.github.com'
        git add index.html
        git commit -m "오늘의 주식 데이터 업데이트"
        git push

