name: 매일 주식 블로그 쓰기

on:
  schedule:
    - cron: '0 23 * * *' # 매일 아침 8시 실행
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write # ⭐️ [중요] 로봇에게 '글쓰기' 권한을 주는 마법의 코드!

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 내 코드 가져오기
      uses: actions/checkout@v3

    - name: 파이썬 설정하기
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 필요한 도구 설치
      run: pip install finance-datareader

    - name: 로봇 실행! (글 쓰기)
      run: python main.py

    - name: 결과물 저장하고 퇴근하기
      run: |
        git config --global user.name 'StockBot'
        git config --global user.email 'bot@noreply.github.com'
        git add index.html
        git commit -m "오늘의 주식 데이터 업데이트" || echo "변경사항이 없어서 넘어갑니다."
        git push
