name: ë§¤ì¼ ì£¼ì‹ ë¸”ë¡œê·¸ ì“°ê¸°

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ ë²„íŠ¼

permissions:
  contents: write # â­ï¸ ì“°ê¸° ê¶Œí•œ í•„ìˆ˜!

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: ë‚´ ì½”ë“œ ê°€ì ¸ì˜¤ê¸°
      uses: actions/checkout@v3
       with:
        ref: 'main'  # ğŸ‘ˆ [ì¤‘ìš”] "ë¬´ì¡°ê±´ ìµœì‹  main ë²„ì „ì„ ê°€ì ¸ì™€!" ë¼ëŠ” ëœ»
        fetch-depth: 0 # ëª¨ë“  ê¸°ë¡ì„ ë‹¤ ìƒˆë¡œê³ ì¹¨í•´ì„œ ê°€ì ¸ì˜¤ë¼ëŠ” ëœ»

    - name: íŒŒì´ì¬ ì„¤ì •í•˜ê¸°
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: í•„ìš”í•œ ë¼ì´ë¸ŒëŸ¬ë¦¬ ì„¤ì¹˜
      run: |
        pip install finance-datareader beautifulsoup4 lxml

    - name: ë¡œë´‡ ì‹¤í–‰! (ì—ëŸ¬ë‚˜ë©´ ë©ˆì¶°!)
      run: |
        python main.py
        cat index.html # â­ï¸ ì‹¤í–‰ ì§í›„, íŒŒì¼ ë‚´ìš©ì´ ì§„ì§œë¡œ ë°”ë€Œì—ˆëŠ”ì§€ í™”ë©´ì— ì¶œë ¥í•´ë³´ê¸°

    - name: ê²°ê³¼ë¬¼ ì €ì¥í•˜ê³  í‡´ê·¼í•˜ê¸°
      run: |
        git config --global user.name 'StockBot'
        git config --global user.email 'bot@noreply.github.com'
        git add index.html
        git commit -m "ì˜¤ëŠ˜ì˜ ì£¼ì‹ ë°ì´í„° ì—…ë°ì´íŠ¸"
        git push

